version: '2.13.0'

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - my-network
    env_file:
      - .env
    restart: on-failure

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp-volume:/var/www/html
    depends_on:
      - mariadb
    networks:
      - my-network
    restart: on-failure

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    # volumes:
      # - db-volume:/var/lib/mysql
    networks:
      - my-network
    restart: on-failure

volumes:
  wp-volume:
    driver_opts:
      device: /Users/amentag/wordpress
      type: none
      o: bind
  db-volume:
    driver_opts:
      device: /Users/amentag/mariadb
      type: none
      o: bind

networks:
  my-network:
    name: my-network
