version: '2.13.0'

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:amentag
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - amentag-network
    env_file:
      - .env
    restart: on-failure

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:amentag
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp-volume:/var/www/html
    depends_on:
      - mariadb
    networks:
      - amentag-network
    restart: on-failure

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:amentag
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - amentag-network
    restart: on-failure

volumes:
  wp-volume:
    driver_opts:
      device: /home/amentag/data/wordpress
  db-volume:
    driver_opts:
      device: /home/amentag/data/mariadb

networks:
  amentag-network:
    name: amentag-network