version: '3'

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - my-network
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp-volume:/var/www/html
    depends_on:
      - mariadb
    networks:
      - my-network

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:  
      - db-volume:/var/lib/mysql/
    networks:
      - my-network

volumes:
  wp-volume:
  db-volume:

networks:
  my-network:
